app:
  environment: dev
spring:
  application:
    name: study
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
